import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Image from "next/image";
import bgImg from '../public/sky.svg';
import rawan from '../public/rawan.svg';
import jena from '../public/jena.svg';
import rama from '../public/rama.svg';
import shukran from '../public/shukran.svg';
import mom from '../public/mom.svg';
import dad from '../public/dad.svg';
import 'animate.css';

export default function Home() {
  const classFilters = {
    1: 'Rawan',
    2: 'Shukran',
    4: 'Rama',
    8: 'Jena',
    16: 'Mom',
    32: 'Dad'
  };

  const [input, setInput] = useState(""); // Initialize input state with an empty string
  const [animateCharacters, setAnimateCharacters] = useState(false);

  const handleInputChange = event => {
    const inputValue = event.target.value;
    setInput(inputValue);
    setAnimateCharacters(!!inputValue); // Set animateCharacters to true if inputValue is not empty
  };

  const getBobbleStyle = flagValue => {
    return animateCharacters && (input & flagValue) > 0 ? 
      { animation: 'slideInFromLeft 1s forwards, fadeIn 1s forwards' } : 
      { display: 'none' };
  };

  return (
    <>
    <div className={styles.body}>
      <Head>
        <title>Aladdin Family Vacation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/rawan.svg" />
      </Head>
      <Header />
      <main className={styles.main}>
      <div className={styles.container}>
        <div className={styles.bgImg}>
          <Image 
            src={bgImg} 
            alt="sky"
            layout="fill"
            fill={true}
            priority={true}
            objectFit="cover"
          />
        </div>

        <div className={styles.bitmask}>
          <input
            id="input"
            type="text"
            placeholder="Bitmask Number"
            value={input}
            onChange={handleInputChange}
          />
          <table>
            <tbody>
              {Object.keys(classFilters).map(item => (
                <tr key={item} style={input & item ? { backgroundColor: 'var(--light-blue)' } : null}>
                  <td>{item}</td>
                  <td>{classFilters[item]}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
                
                {/* characters */}
        
          <Image 
            src={rawan}
            className={styles.bobble}
            style={getBobbleStyle(1)}
            alt="rawan"
          />
          <Image 
            src={shukran}
            className={styles.bobble}
            style={getBobbleStyle(2)}
            alt="shukran"
          />
          <Image 
            src={rama}
            className={styles.bobble}
            style={getBobbleStyle(4)}
            alt="rama"
          />
          <Image 
            src={jena}
            className={styles.bobble}
            style={getBobbleStyle(8)}
            alt="jena"
          />
          <Image 
            src={mom}
            className={styles.bobble}
            style={getBobbleStyle(16)}
            alt="mom"
          />
          <Image 
            src={dad}
            className={styles.bobble}
            style={getBobbleStyle(32)}
            alt="dad"
          />
        </div>
      </main>
      <Footer />
      </div>
    </>
  );
}
