import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Image from "next/image";
import bgImg from '../public/sky.svg';
import rawan from '../public/rawan.svg';
import jena from '../public/jena.svg';
import rama from '../public/rama.svg';
import shukran from '../public/shukran.svg';
import mom from '../public/mom.svg';
import dad from '../public/dad.svg';
import cloud from '../public/cloud.svg';


export default function Home() {
  
  // Family Members
  const classFilters = {
    // key : value
    1: 'Rawan',
    2: 'Shukran',
    4: 'Rama',
    8: 'Jena',
    16: 'Mom',
    32: 'Dad'
  }

  const [input, setInput] = useState();
  // 3
  // 2  &  2 Remainder 1
  // 1  &  1 Remainder 0
  // 9 
  // 8 & 8 Remainder 1
  // 1 & 1 Remainder 0
  const getClassStyle = flagValue => (input & flagValue) > 0 ? {backgroundColor: 'yellow'} : null;

  return (
    <>
      <Head>
        <title>Aladdin Family Vacation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/rawan.svg" />
        
      </Head>
      <Header />
      <main className={`${styles.main}`}>
        <div className={styles.bgImg}>
          <Image 
            src={bgImg} 
            alt="sky"
            layout="fill"
            objectFit="cover"
          />
        </div>

        <div className={styles.bitmask}>
          <input
            id="input"
            type="text"
            placeholder="Bitmask Number"
            value={input}
            onChange={event => setInput(event.target.value)}
          />
          <table>
            <tbody>
              {
                Object.keys(classFilters).map(item => (
                  <tr key={item} style={getClassStyle(item)}>
                    <td>{item}</td>
                    <td>{classFilters[item]}</td>
                  </tr>
                ))
              }
            </tbody>
          </table>
        </div>

        <div className={styles.bobble}>
          {/* cloud for characters to hide */}
          <Image 
            src={cloud}
            alt="cloud"
          />
          {/* characters */}
          <Image 
            src={rawan}
            alt="rawan"
          />
          <Image 
            src={jena}
            alt="jena"
          />
          <Image 
            src={rama}
            alt="rama"
          />
          <Image 
            src={shukran}
            alt="shukran"
          />
          <Image 
            src={mom}
            alt="mom"
          />
          <Image 
            src={dad}
            alt="dad"
          />
        </div>
      </main>
      <Footer />
    </>
  );
}
